import { useEffect, useState } from 'react';
import { api } from '../../api/client';
import type { AdminCoverageSlot, AdminPoll, AdminSummary } from '../../types';
import { CoverageHeatmap } from './CoverageHeatmap';
import { PollLog } from './PollLog';

function StatCard({ label, value, sub }: { label: string; value: string | number; sub?: string }) {
  return (
    <div className="stat-card">
      <div className="stat-card-value">{value}</div>
      <div className="stat-card-label">{label}</div>
      {sub && <div className="stat-card-sub">{sub}</div>}
    </div>
  );
}

function formatDate(iso: string | null) {
  if (!iso) return '—';
  return new Date(iso).toLocaleString(undefined, {
    month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
  });
}

export function AdminPage() {
  const [summary, setSummary] = useState<AdminSummary | null>(null);
  const [polls, setPolls] = useState<AdminPoll[]>([]);
  const [coverage, setCoverage] = useState<AdminCoverageSlot[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      api.admin.summary(),
      api.admin.polls(200),
      api.admin.coverage(),
    ])
      .then(([s, p, c]) => {
        setSummary(s);
        setPolls(p);
        setCoverage(c);
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  const maxPollCount = coverage.length > 0 ? Math.max(...coverage.map(c => c.poll_count)) : 0;
  const minPollCount = coverage.length > 0 ? Math.min(...coverage.map(c => c.poll_count)) : 0;

  return (
    <div className="admin-page">
      <div className="admin-header">
        <h1 className="admin-title">Data Collection Status</h1>
        {summary && (
          <div className="admin-subtitle">
            {summary.real_last_poll
              ? `Last poll: ${formatDate(summary.real_last_poll)}`
              : 'No real polls yet — start the collector to begin collecting live data.'}
          </div>
        )}
      </div>

      {loading && <div className="loading">Loading…</div>}

      {summary && (
        <>
          {/* Real data stats */}
          <section className="admin-section">
            <h2 className="admin-section-title">Live collection</h2>
            <p className="admin-section-desc">
              Counts from the real-time collector only. Seeded mock data (used to bootstrap the
              probability model) is excluded from all numbers below.
            </p>
            <div className="stat-cards">
              <StatCard
                label="Real polls"
                value={summary.real_polls.toLocaleString()}
                sub={summary.real_polls === 0 ? 'collector not yet started' : `${summary.real_span_days}d of real data`}
              />
              <StatCard
                label="Real snapshots"
                value={summary.real_rows.toLocaleString()}
                sub={summary.real_station_count > 0 ? `${summary.real_station_count.toLocaleString()} stations` : '—'}
              />
              <StatCard
                label="Polls (last 24h)"
                value={summary.real_polls_last_24h}
                sub={`of ${summary.expected_polls_per_day} expected`}
              />
              <StatCard
                label="Coverage depth"
                value={coverage.length > 0 ? `${minPollCount}–${maxPollCount}` : '—'}
                sub="real polls per 5-min window"
              />
              <StatCard
                label="Collector started"
                value={formatDate(summary.real_first_poll)}
              />
            </div>
          </section>

          {/* Seeded data context note */}
          <section className="admin-section">
            <div style={{
              background: '#f7f8fa',
              border: '1px solid #ebedf0',
              borderRadius: 12,
              padding: '14px 18px',
              fontSize: 13,
              color: '#6c727e',
              lineHeight: 1.6,
            }}>
              <strong style={{ color: '#16181d' }}>About the seeded data</strong>
              <br />
              The database also contains {summary.seeded_rows.toLocaleString()} synthetic rows
              ({summary.seeded_polls.toLocaleString()} mock polls) generated by the seeder script.
              These are used to bootstrap the probability model before enough real data has accumulated.
              They are tagged <code>is_seeded = 1</code> and are automatically phased out of
              probability calculations as 90 days of real data accumulates. They do not appear in
              any of the stats above.
            </div>
          </section>

          {/* Coverage heatmap — real data only */}
          <section className="admin-section">
            <h2 className="admin-section-title">Weekly coverage heatmap</h2>
            <p className="admin-section-desc">
              Each cell is a 5-minute window in the week, showing real polls only.{' '}
              {coverage.length === 0
                ? 'No real data yet — cells will fill in as the collector runs.'
                : <>After one week every cell shows 1. After two weeks, 2. <strong>Coverage</strong> view shows depth; switch to probability views to see availability patterns.</>
              }
            </p>
            {coverage.length > 0
              ? <CoverageHeatmap data={coverage} />
              : <div className="loading" style={{ textAlign: 'left', padding: '24px 0' }}>No real polls recorded yet. The heatmap will populate once the collector starts running.</div>
            }
          </section>

          {/* Poll log — real only */}
          <section className="admin-section">
            <h2 className="admin-section-title">Recent polls</h2>
            <p className="admin-section-desc">
              {polls.length > 0
                ? `One row per 5-minute collection cycle. A complete poll captures all ~${summary.real_station_count.toLocaleString()} active stations.`
                : 'No real polls yet. Start the collector to see entries here.'}
            </p>
            {polls.length > 0
              ? <PollLog polls={polls} />
              : <div className="loading" style={{ textAlign: 'left', padding: '0' }}>Waiting for first poll…</div>
            }
          </section>
        </>
      )}
    </div>
  );
}
